import { Playfair } from "next/font/google";
import "./globals.css";

const playfair = Playfair({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${playfair.className} h-full antialiased inter bg-[#ECE5D7]`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
